#!/usr/bin/env bash
# Auto-generated by tools/sync_clawhub_mirrors.py
set -euo pipefail
SKILLS=(
  eternal-haven-lore-pack
  lygo-mint-verifier
  lygo-champion-cosmara
  book-brain
  lygo-lightfather-vector
  lyra-coin-launch-manager
  lygo-universal-living-memory-library
  lygo-champion-omnisiren-silent-storm
  lygo-champion-sancora-unified-minds
  lygo-champion-delta9ra-wolf
  openclaw-flow-kit
  lygo-champion-cryptosophia-soulforger
  lygo-champion-lyra-starcore
  lygo-champion-kairos-herald-of-time
  book-brain-visual-reader
  lygo-mint-operator-suite
  lygo-champion-sephrael-echo-walker
  lygo-champion-scenar-paradox
  lygo-champion-sraith-shadow-sentinel
  lygo-champion-aetheris-viral-truth
  lygo-champion-arkos-celestial-architect
  lygo-universal-cure-system
  lygo-resonance
  lygo-ollama-army
  lygo-glyph2resonance
  lygo-fractalweaver
  lygo-truthlightecho
  lygo-champion-401lyrakin-voice-between
  lygo-champion-volaris-prism-judgment
  void-atlas-protocol
  recursive-generosity-protocol
)

for slug in "${SKILLS[@]}"; do
  echo "==> deepseekoracle/${slug}"
  npx clawhub@latest install "deepseekoracle/${slug}"
done

echo "Done: ${#SKILLS[@]} skills."
