"""P3 prompt engine — sovereign variants (local templates, no external API)."""

from __future__ import annotations

import hashlib
import json
from typing import Any

from .consensus import P3VortexConsensus

SOVEREIGN_HEADER = """# LYGO Sovereign Prompt Variant
# Generated by LPIS — stack P0-P5 hooks; user reviews before any live implant.
# Target: {target}
# Layers: {layers}

## Cognitive contract
- Plan before execute; verify with stack tools.
- No secrets in prompts; consent for publish/post.
- Lattice health: run verify_lattice_alignment before claiming ALIGNED.

"""


class PromptEngine:
    def __init__(self) -> None:
        self.consensus = P3VortexConsensus()

    def generate(
        self,
        base_content: str,
        *,
        target_model: str = "grok",
        layers: list[str] | None = None,
        base_id: str = "base",
    ) -> dict[str, Any]:
        layers = layers or ["P0", "P1", "P3", "P5"]
        header = SOVEREIGN_HEADER.format(target=target_model, layers=",".join(layers))
        # Trim enormous bases for variant shell; full body referenced by id
        excerpt = base_content[:12000]
        if len(base_content) > 12000:
            excerpt += "\n\n[... LPIS: truncated for variant shell; full text in vault ...]\n"
        body = header + "\n## Base excerpt\n\n" + excerpt
        variant_id = f"sovereign_{target_model}_{hashlib.sha256(body.encode()).hexdigest()[:10]}"
        bundle = {
            "variant_id": variant_id,
            "base_id": base_id,
            "target_model": target_model,
            "layers": layers,
            "content": body,
        }
        consensus = self.consensus.achieve_consensus({"agents": ["local-a", "local-b"], "variant": variant_id})
        bundle["consensus"] = consensus
        bundle["approved"] = consensus.get("consensus_found", True)
        return bundle