#!/usr/bin/env python3
"""
Load Biophase7 API stack into process env (local testing only).

Never commit loaded secrets — .env and *.local.env are gitignored.
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path
from typing import Dict

ROOT = Path(__file__).resolve().parents[1]

# Override with LYGO_BIOPHASE7_VAULT (full path to stack .txt in restore tree).
DEFAULT_VAULT_CANDIDATES = [
    Path(
        os.environ.get(
            "LYGO_BIOPHASE7_VAULT",
            r"I:\E Drive\LYRA SYSTEM RETORE\FINAL RESTORE\ALL SEALS\220+\New folder\2026Biophase7",
        )
    ),
]

KEY_LINE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")
BARE_TOKEN = re.compile(r"^(nvapi-[A-Za-z0-9_-]+|xai-[A-Za-z0-9_-]+|AIza[A-Za-z0-9_-]+)$")


def _resolve_vault_file(path: Path) -> Path:
    if path.is_file():
        return path
    if path.is_dir():
        hits = sorted(path.glob("xai-*.txt"))
        if hits:
            return hits[0]
        hits = sorted(path.glob("*Biophase7*.txt"))
        if hits:
            return hits[0]
    raise FileNotFoundError(f"Biophase7 vault not found: {path}")


def parse_vault(text: str) -> Dict[str, str]:
    out: Dict[str, str] = {}
    bare_xai: list[str] = []
    bare_nv: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = KEY_LINE.match(line)
        if m:
            out[m.group(1).strip()] = m.group(2).strip().strip('"').strip("'")
            continue
        if BARE_TOKEN.match(line):
            if line.startswith("nvapi-"):
                bare_nv.append(line)
            elif line.startswith("xai-"):
                bare_xai.append(line)
            elif line.startswith("AIza"):
                out.setdefault("GOOGLE_API_KEY", line)
    if bare_nv and "NVIDIA_API_KEY" not in out:
        out["NVIDIA_API_KEY"] = bare_nv[0]
    if len(bare_xai) >= 1 and "XAI_API_KEY_ALT" not in out:
        out["XAI_API_KEY_ALT"] = bare_xai[0]
    if len(bare_xai) >= 2 and "XAI_API_KEY_MAIN" not in out:
        out["XAI_API_KEY_MAIN"] = bare_xai[1]
    return out


def apply_aliases(vars_map: Dict[str, str]) -> Dict[str, str]:
    """Prefer alt xAI for LYRA LLM burn; single alias for adapters."""
    if not os.environ.get("XAI_API_KEY"):
        alt = vars_map.get("XAI_API_KEY_ALT") or vars_map.get("XAI_API_KEY")
        main = vars_map.get("XAI_API_KEY_MAIN")
        vars_map.setdefault("XAI_API_KEY", alt or main or "")
    if not os.environ.get("GEMINI_API_KEY"):
        vars_map.setdefault(
            "GEMINI_API_KEY",
            vars_map.get("GEMINI_API_KEY") or vars_map.get("GOOGLE_API_KEY") or "",
        )
    return vars_map


def load_vault(
    vault: Path | None = None,
    *,
    apply: bool = True,
    overwrite: bool = False,
) -> Dict[str, str]:
    candidates = [vault] if vault else []
    for c in DEFAULT_VAULT_CANDIDATES:
        if c not in candidates:
            candidates.append(c)
    last_err: Exception | None = None
    resolved: Path | None = None
    for cand in candidates:
        if cand is None:
            continue
        try:
            resolved = _resolve_vault_file(Path(cand))
            break
        except FileNotFoundError as exc:
            last_err = exc
    if resolved is None:
        raise FileNotFoundError(str(last_err or "no vault path"))

    vars_map = apply_aliases(parse_vault(resolved.read_text(encoding="utf-8", errors="replace")))
    if apply:
        for key, val in vars_map.items():
            if not val:
                continue
            if overwrite or not os.environ.get(key):
                os.environ[key] = val
    vars_map["_vault_path"] = str(resolved)
    return vars_map


def write_local_env(vars_map: Dict[str, str], dest: Path) -> Path:
    dest = dest.resolve()
    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by load_biophase7_vault.py — gitignored; do not commit",
        f"# source: {vars_map.get('_vault_path', 'unknown')}",
        "",
    ]
    for key in sorted(k for k in vars_map if not k.startswith("_")):
        lines.append(f"{key}={vars_map[key]}")
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return dest


def main() -> int:
    parser = argparse.ArgumentParser(description="Load Biophase7 API stack into env / .env")
    parser.add_argument("--vault", type=Path, default=None, help="File or 2026Biophase7 directory")
    parser.add_argument(
        "--write-env",
        type=Path,
        default=ROOT / ".env",
        help="Write gitignored .env (default: repo .env)",
    )
    parser.add_argument("--no-apply", action="store_true", help="Only write file, do not set os.environ")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing env vars")
    parser.add_argument("--dry-run", action="store_true", help="Print key names only")
    args = parser.parse_args()
    vars_map = load_vault(args.vault, apply=not args.no_apply, overwrite=args.overwrite)
    if args.dry_run:
        print("Keys loaded:", ", ".join(sorted(k for k in vars_map if not k.startswith("_"))))
        print("Vault:", vars_map.get("_vault_path"))
        return 0
    path = write_local_env(vars_map, args.write_env)
    print(f"Wrote {path} ({len(vars_map) - 1} vars) from {vars_map.get('_vault_path')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())